name: Issue comments

on:
  issue_comment:
    types: [created]
    
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello
        run: echo 'Hello'

      - name: Debug
        uses: actions/github-script@v4
        with:
          script: console.log(context);

      - name: Startup
        uses: actions/github-script@v4
        with:
          script: |
            // Make sure we're being spoken to
            if (context.payload.comment.body !== '/hi') {
                github.log.info('Not for us');
                return;
            }
             
            // Check the permissions of the sender 
            const response = await github.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: context.payload.sender.login
            });
            const permission = response.data.permission;
            if (permission !== 'amin' && permission !== 'write') {
                await github.reactions.createForIssueComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    comment_id: context.payload.comment.id,
                    content: 'confused'
                });
                await github.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: '>/hi\n\nThis command can only be used by users with write access to the repository'
                });                    
                core.setFailed(`User ${context.payload.sender.login} has insufficient permissions`);
                return;
            }
            
            // Indicate that we're about to start work
            await github.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: 'rocket'
            });
