name: Issue comments

on:
  issue_comment:
    types: [created]
    
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello
        run: echo 'Hello'

      - name: Check permission
        uses: actions/github-script@v3
        with:
          script: |
            const { repo: { owner, repo }, payload: { sender: { login : username } } } = context;
            const response = await github.repos.getCollaboratorPermissionLevel({ owner, repo, username });
            console.log(response.data.permission);
