name: prt
on:
  pull_request_target:
    paths:
      - abc

jobs:
  build:
    permissions: none
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: touch a

      - uses: actions/upload-artifact@v2
        with:
          name: thing
          path: a

  upload:
    environment: allisoninc/node-cache upload
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: thing

      - name: lessee
        run: ls -lR

      - name: Depoy!
        run: |
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > private-key
          chmod 600 private-key
          ssh -i private-key git@github.com


